### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by schignel** [alexbruy/qtutor#1] opened 2019-06-20 22:18 UTC
Hi @alexbruy, I'm trying to install the QTutor plug-in (by accessing your repository from with QGIS) and get the following error upon installing it. Do you have any suggestions? Thanks!
```
`Couldn't load plugin 'qtutor' due to an error when calling its initGui() method 

NameError: name 'self' is not defined 
Traceback (most recent call last):
  File "C:/Users/steve/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qtutor\lesson.py", line 245, in fromYaml
    lesson.addMenuStep(step['menu'], name, description)
  File "C:/Users/steve/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qtutor\lesson.py", line 145, in addMenuStep
    raise Exception(self.tr('Can not find menu "{}".'.format(menuString)))
Exception: Can not find menu "Layer|Create Layer|New Temporary Scratch Layer...".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 344, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/steve/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qtutor\qtutorplugin.py", line 89, in initGui
    lessonsRegistry.loadLessons()
  File "C:/Users/steve/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qtutor\qtutorregistry.py", line 56, in loadLessons
    self._loadFromDirectory(os.path.join(pluginPath, 'lessons'))
  File "C:/Users/steve/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qtutor\qtutorregistry.py", line 121, in _loadFromDirectory
    lesson = Lesson.fromYaml(os.path.join(root, 'lesson.yaml'))
  File "C:/Users/steve/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qtutor\lesson.py", line 247, in fromYaml
    QgsMessageLog.logMessage(self.tr('Can not load lesson from {}:\n{}'.format(lessonFile, traceback.format_exc())), 'QTutor')
NameError: name 'self' is not defined


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.6.3-Noosa Noosa, 0c5774c068 

Python Path:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/steve/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/steve/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/steve/AppData/Roaming/QGIS/QGIS3\profiles\default/python`
```

**Comment by alexbruy** [comment] 2019-06-22 08:27
Generally speaking this is not a bug, plugin just can not load built-in demo lesson because menu entry used in it was renamed. Plugin itself should be fully functional.

Should be fixed in 0.1.1.

**Closed by alexbruy** 2019-06-22 08:27 UTC
